//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public int id { get; set; }
        public string name { get; set; }
        public string instructor { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public Nullable<int> enrollments { get; set; }
        public string image { get; set; }
    }
}
