//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_Table
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string location { get; set; }
        public string password { get; set; }
        public string repeat_password { get; set; }
    }
}
